<template><CrmListPage title="报价" description="基于商机和价目表创建、提交并跟踪报价审批" endpoint="/quotes" :columns="columns" :create-fields="fields" create-endpoint="/quotes" :create-payload="createPayload" :actions="actions" /></template>
<script setup lang="ts">
import type { CrmAction, CrmColumn, CrmField } from '../components/CrmListPage.vue'
import CrmListPage from '../components/CrmListPage.vue'
const columns: CrmColumn[] = [{ title: '报价编号', dataIndex: 'quoteNo' }, { title: '商机 ID', dataIndex: 'opportunityId' }, { title: '客户 ID', dataIndex: 'customerId' }, { title: '状态', dataIndex: 'status' }, { title: '当前版本', dataIndex: 'currentVersionNo' }, { title: '有效期至', dataIndex: 'validUntil' }, { title: '操作', dataIndex: 'operations' }]
const fields: CrmField[] = [{ key: 'opportunityId', label: '商机 ID', required: true }, { key: 'priceListId', label: '价目表 ID', required: true }, { key: 'validUntil', label: '有效期至', required: true, type: 'date' }, { key: 'productId', label: '产品 ID', required: true }, { key: 'priceItemId', label: '价目项 ID', required: true }, { key: 'quantity', label: '数量', required: true, type: 'number', precision: 2 }, { key: 'unitPrice', label: '单价', required: true, type: 'number', precision: 2 }, { key: 'discountRate', label: '折扣率', required: true, type: 'number', precision: 4 }]
function createPayload(model: Record<string, any>) { return { opportunityId: model.opportunityId, priceListId: model.priceListId, validUntil: model.validUntil, lines: [{ productId: model.productId, priceItemId: model.priceItemId, quantity: model.quantity, unitPrice: model.unitPrice, discountRate: model.discountRate }] } }
const actions: CrmAction[] = [{ label: '提交审批', path: row => `/quotes/${row.id}/actions/submit`, idempotent: true, visible: row => row.status === 'DRAFT', payload: row => ({ rootVersion: row.version, version: row.version, approvalDefinitionCode: 'QUOTE_APPROVAL' }) }, { label: '标记过期', path: row => `/quotes/${row.id}/actions/expire`, visible: row => row.status === 'DRAFT' || row.status === 'APPROVED', payload: row => ({ rootVersion: row.version, version: row.version }) }]
</script>
